### PR TITLE
Failing tests for submit value

### PR DESCRIPTION
**Pull request by Tekki**
Here are some failing tests for #3.
I've added a hidden field with name 'p' and a second submit button with the same name. Submit the form without clicking a button should return `p = P0`, click on the first button `p = P1` and click on the second `p = P2`.

### CODE REVIEW

**Comment by kiwiroy** [comment]
Thanks for this, very helpful. Ignoring [these](https://travis-ci.com/kiwiroy/mojo-transaction-http-role-mechanize/jobs/219148075#L483-L484) :wink:, `p` should be an array i.e. `p=P0&p=P1` in the two submit cases. I think I have a fix.

**Comment by Tekki** [comment]
If we make an array the main question is if the order of the parameters is preserved. I'll have to check this against a real world application and probably have no time before the week end.
In any case this module already looks much better than HTML::Form! And it's a good example about how to use roles.

**Comment by kiwiroy** [comment]
I've been looking at [this](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission), [this](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-submission-algorithm) and [submit spec](https://html.spec.whatwg.org/multipage/input.html#submit-button-state-(type=submit)). Tree order is mentioned there, as is default button, which I also made edits to today. For the submit button value, `around val` never calls `$self->$orig(@args)`, because the following is different to `Mojo::DOM->val`. I guess really it should adjust locale/gettext...

https://github.com/kiwiroy/mojo-transaction-http-role-mechanize/blob/d8f853938d2dec085e56f665125921d29287fe07/lib/Mojo/DOM/Role/Form.pm#L58-L63

**Comment by kiwiroy** [comment]
Quick test at https://www.w3schools.com/html/tryit.asp?filename=tryhtml_elem_datalist with following content seems like order is tree order.
```
<!DOCTYPE html>
<html>
<body>

<form action="/action_page.php">
  <input name=p value=P0 type=hidden />
  <input type="submit" name=p value=P1 />
  <input name=p value=2P type=hidden />
</form>

</body>
</html>
```

**Pull request merged**
